---
- ansible.builtin.include_vars: openrc-service-vars.yml
- name: Templatize {{ openrc_initd }} service script
  become: true
  become_user: root
  ansible.builtin.template:
    src: init.d-template.j2
    dest: '{{ openrc_initd }}'
    mode: '751'
- name: Ensuring {{ openrc_config.name }} service is {{ openrc_eff_state }}
  become: true
  become_user: root
  service:
    name: '{{ openrc_config.name }}'
    state: '{{ openrc_eff_state }}'
